milestone 1 initial commit
grace-mugoiri/react-bookstore pull request #1
Opened 2020-01-20 16:08 UTC by grace-mugoiri

2020-01-20 21:14 UTC, jofer86 requested changes
## :wave: :wave: Hello, I'm here to the review on this PR.
- Below you are going to find some changes that are **required** for you to do in order for this project to be approved, please tend to them.
- You need to add a descriptive README file to your project as that is also a Hard Requirement to consider this project a valid one. You can read all about it [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-01-20 21:14 UTC, jofer86 commented on bookstore/.eslintrc.json
> +  }
- This .eslintrc.json file is not the one provided by Microverse, please refer to [the Microverse linter repo for react/redux](https://github.com/microverseinc/linters-config/tree/master/react-redux); for a proper configuration of our linter configuration files. As the file should look like this: 
![image](https://user-images.githubusercontent.com/46115725/72757581-f6807100-3b95-11ea-9f86-85df9ecc0e12.png)

2020-01-20 21:14 UTC, jofer86 commented on bookstore/eslint.config
> +}
Please do delete this file as it is not going to be used.

2020-01-20 21:14 UTC, jofer86 commented on bookstore/.stickler.yml
> +    - '.eslintrc.json'
This file should look like the one in the [Microverse Linters Repo](https://github.com/microverseinc/linters-config/blob/master/react-redux/.stickler.yml)
![image](https://user-images.githubusercontent.com/46115725/72757810-99d18600-3b96-11ea-8f2f-a317ae5c3992.png)

2020-01-21 07:43 UTC, bolah2009 approved these changes
Hi @grace-mugoiri 

@jofer86  seems to miss this but you need a descriptive PR description. Please see [this pathwright lesson for detailed instructions](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

> Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good luck with your next milestones. :star2: 

Please see the comment below and update PR description before merging.

Cheers
[Bola](https://bolabuari.com/)

2020-01-21 07:43 UTC, bolah2009 commented on src/serviceWorker.js
> +  window.location.hostname === 'localhost'
[Optional]

I would recommend deleting this file

2020-01-22 09:50 UTC, merged