Components and redux store
grace-mugoiri/react-bookstore pull request #2
Opened 2020-01-22 09:56 UTC by grace-mugoiri

Kindly review my work for milestone which deals with project structure and actions (reducers) for this section.

2020-01-22 15:19 UTC, JamesOkunlade commented on src/App.js
> +/* eslint-disable import/extensions */
Your `app.js` component that should go into the `src/components/` folder.

2020-01-22 15:31 UTC, JamesOkunlade commented on src/components/Book.js
> +    const book = this.props.book;
Destructuring the book props in this case should be `const { book} = this.props.book;`

2020-01-22 15:47 UTC, JamesOkunlade commented on src/containers/BooksForm.js
> +      bookGenres: ['Action and Adventure', 'Anthology', 'Chick lit', 'Crime', 'Drama', 'Fantasy'],
Your list of categories will be in a normal `const` data type and not in the `state`. What should go into the `state` are `title` and `category` 

```
this.state = {
      title: '',
      category: 'Action',
    };
```

2020-01-22 15:56 UTC, JamesOkunlade commented on src/containers/BooksForm.js
> +    const { bookGenres } = this.state;
Remove this line as your genres will not be coming from the `state`. Implement my above point instead and also write these lines of code to map all the genres to display in the select options:

```
const bookGenres = ['Action and Adventure', 'Anthology', 'Chick lit', 'Crime', 'Drama', 'Fantasy'];

const bookOptions = bookGenres.map(category => <option key={category} value={category}>{category}</option>);

```

2020-01-22 16:06 UTC, JamesOkunlade requested changes
# ♻️ Changes required

**Hello guys,**

Great job so far 🙂 I have left some comments for you to make corrections on. Please check them out below.

Also, remove all the files that are not needed anymore from your project, like the `App.test.js`, `logo.svg`,  and `setupTests.js` all in your `src` folder and the `.png`s in your `public` folder.

Request for re-review when you're done. 

**Goodluck** 😁  
[James](https://twitter.com/JamesOkunlade)

2020-01-23 12:56 UTC, bellom approved these changes
## Hi @grace-mugoiri   :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-23 13:27 UTC, merged